export const Images = {
    Image:"./asets/sumit_profile.jpg",
    Image1:"./asets/plant.jpg",
    Image2:"./asets/samman.jpg",
    Image3:"./asets/police.jpg",
    Image4:"./asets/raktdan.jpg",
    Image5:"./asets/achivement.jpg",
    Image6:"./asets/naugachia.jpg",
    Image7:"./asets/div_line_blue.png",
    Image8:"./asets/gurudev.jpg",
    Image9:"./asets/deputy cm 2.jpg",
    Image10:"./asets/deputy cm.jpg",
    Image11:"./asets/sahanwaz.jpg",
    Image12:"./asets/horizontal-img.jpg",
    Image13:"./asets/tiranga.jpg",
    Image14:"./asets/black.webp",
    Image15:"./asets/tiranga2.webp",
    // Image16:"./asets/sumit-img.png",
    Image16:"./asets/Sumeet-designstyle-kiddo-m.png",
    Image17:"./asets/vikash-vaibhav.jpg",
    Image18:"./asets/swami-samman.jpg",
    Image19:"./asets/rail.jpg",
    Image20:"./asets/raktdan-2.jpg",
    Image21:"./asets/wheelchair.jpg",
    Image22:"./asets/sumit-singh.jpg",
    Image23:"./asets/vijay.jpg",
    Image24:"./asets/samrat.jpg",
    Image25:"./asets/samman-2.jpg",
    Image26:"./asets/s-logo.jpg",
}